import type { Report } from "./types";

/** Produce a commit-ready TS module string for `data/reports/{slug}.ts`. */
export function reportToTsFile(report: Report): string {
  const body = JSON.stringify(report, null, 2);
  return `// Generated by /admin/new-report — drop into data/reports/${report.slug || "{slug}"}.ts
import type { Report } from "@/lib/report/types";

export const report: Report = ${body};

export default report;
`;
}
