#!/usr/bin/env node
// One-off lookup against the live Rex tenant: dumps lead types, lead sources
// and admin users so the values in lib/rex/lead-config.ts can be filled in.
// Runs against the same Wings API as the rest of the app, with the same creds
// (REX_USERNAME / REX_PASSWORD / optional REX_ACCOUNT_ID).
//
//   node --env-file=.env.local scripts/rex-lookup.mjs
//
// Or pipe to a file the team can review:
//
//   node --env-file=.env.local scripts/rex-lookup.mjs > docs/REX-LOOKUP.md
//
// This is a one-shot; once the lead-config is populated and verified, the
// script doesn't need to run again until the tenant adds new lead types or
// reassigns leads to a different user.

const BASE = process.env.REX_API_BASE ?? "https://api.rexsoftware.com";
const USER = process.env.REX_USERNAME;
const PASS = process.env.REX_PASSWORD;
const ACCOUNT_ID = process.env.REX_ACCOUNT_ID;

if (!USER || !PASS) {
  console.error(
    "REX_USERNAME / REX_PASSWORD are required. Pass them via .env.local with:",
  );
  console.error("  node --env-file=.env.local scripts/rex-lookup.mjs");
  process.exit(2);
}

async function login() {
  const res = await fetch(`${BASE}/v1/rex/Authentication/login`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      email: USER,
      password: PASS,
      ...(ACCOUNT_ID ? { account_id: Number(ACCOUNT_ID) } : {}),
      token_lifetime: 3600,
    }),
  });
  const data = await res.json();
  if (!res.ok || data.error || typeof data.result !== "string") {
    throw new Error(`Rex login failed: ${data.error?.message ?? `HTTP ${res.status}`}`);
  }
  return data.result;
}

async function rexCall(token, method, args = {}) {
  const res = await fetch(`${BASE}/v1/rex/${method}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
    },
    body: JSON.stringify(args),
  });
  const data = await res.json();
  if (!res.ok || data.error) {
    throw new Error(data.error?.message ?? `HTTP ${res.status}`);
  }
  return data.result;
}

function unwrap(result) {
  if (Array.isArray(result)) return result;
  if (result && Array.isArray(result.rows)) return result.rows;
  return [];
}

// Try a couple of plausible method names per concept — Rex's Wings surface is
// large and some collections live under different names depending on tenant
// tier. Stop at the first one that returns rows.
async function lookup(token, label, candidates) {
  for (const { method, args } of candidates) {
    try {
      const result = await rexCall(token, method, args);
      const rows = unwrap(result);
      return { label, method, rows };
    } catch (err) {
      // Try the next candidate; record the failure for the report.
      // eslint-disable-next-line no-empty
    }
  }
  return { label, method: null, rows: [], error: "no method succeeded" };
}

function table(rows, columns) {
  if (!rows.length) return "_no rows returned_\n";
  const header = `| ${columns.map((c) => c.label).join(" | ")} |`;
  const divider = `| ${columns.map(() => "---").join(" | ")} |`;
  const body = rows
    .map((r) => `| ${columns.map((c) => formatCell(r[c.key])).join(" | ")} |`)
    .join("\n");
  return `${header}\n${divider}\n${body}\n`;
}

function formatCell(v) {
  if (v == null) return "";
  if (typeof v === "object") return JSON.stringify(v).replace(/\|/g, "\\|");
  return String(v).replace(/\|/g, "\\|").replace(/\n/g, " ");
}

async function main() {
  const token = await login();

  const leadTypes = await lookup(token, "Lead types", [
    { method: "LeadTypes/search", args: { limit: 200 } },
    { method: "AdminLeadTypes/search", args: { limit: 200 } },
  ]);
  const leadSources = await lookup(token, "Lead sources", [
    { method: "LeadSources/search", args: { limit: 200 } },
    { method: "AdminLeadSources/search", args: { limit: 200 } },
  ]);
  const users = await lookup(token, "Admin users", [
    { method: "AdminUsers/search", args: { limit: 200 } },
    { method: "Users/search", args: { limit: 200 } },
  ]);

  const stamp = new Date().toISOString().slice(0, 10);
  process.stdout.write(`# Rex tenant lookup — ${stamp}\n\n`);
  process.stdout.write(
    "Generated by `scripts/rex-lookup.mjs`. Use this to populate" +
      " `lib/rex/lead-config.ts` (the `TODO_REX_LOOKUP_*` sentinels).\n\n",
  );

  process.stdout.write(`## Lead types  _(${leadTypes.method ?? "no method"})_\n\n`);
  process.stdout.write(
    table(leadTypes.rows, [
      { key: "id", label: "id" },
      { key: "text", label: "label" },
      { key: "name", label: "name" },
      { key: "is_active", label: "active" },
    ]),
  );
  process.stdout.write("\n");

  process.stdout.write(`## Lead sources  _(${leadSources.method ?? "no method"})_\n\n`);
  process.stdout.write(
    table(leadSources.rows, [
      { key: "id", label: "id" },
      { key: "text", label: "label" },
      { key: "name", label: "name" },
      { key: "is_active", label: "active" },
    ]),
  );
  process.stdout.write("\n");

  process.stdout.write(`## Admin users  _(${users.method ?? "no method"})_\n\n`);
  process.stdout.write(
    table(users.rows, [
      { key: "id", label: "id" },
      { key: "name", label: "name" },
      { key: "email_address", label: "email" },
      { key: "is_active", label: "active" },
    ]),
  );
  process.stdout.write("\n");

  process.stdout.write("## Next steps\n\n");
  process.stdout.write(
    "1. Pick the `lead_type.id` for each formId mapping in `lib/rex/lead-config.ts`.\n" +
      "2. Pick the `lead_source.id` representing the website. If none exists, ask Matt to add one in **Settings → Lead sources**, then re-run this lookup.\n" +
      "3. Pick the `assignee.id` for Matt (or whoever owns website leads).\n" +
      "4. Replace each `TODO_REX_LOOKUP_*` sentinel and open a small PR.\n",
  );

  for (const r of [leadTypes, leadSources, users]) {
    if (r.error) {
      process.stderr.write(`! ${r.label}: ${r.error}\n`);
    }
  }
}

main().catch((err) => {
  console.error("rex-lookup failed:", err);
  process.exit(1);
});
